# Generated by Django 4.1.7 on 2023-03-07 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchengine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='title',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]